version: "3.2"
volumes:
  database:
  media:
services:
  database:
    image: postgres:11
    environment:
      POSTGRES_DB: taiga
      POSTGRES_PASSWORD: changeme
      POSTGRES_USER: taiga
    stop_signal: SIGINT
    volumes:
      - database:/var/lib/postgresql/data
  server:
    image: taigaio/taiga5:latest
    command:
      - migrate
      # Make sure this command is run only during the initial setup as it will
      # overwrite existing data.
      - populate-db
      - run-server
    healthcheck:
      test: wget -q -t 1 --spider http://localhost:8080/api/v1/
    ports:
      - 8080:8080
    stop_signal: SIGHUP
    volumes:
      - media:/srv/taiga-back/media
